### ISSUE TITLE
Created branch with "install for all users".

### ISSUE THREAD

**Issue by klondikemarlen** [klondikemarlen/chocolatey-packages-automatic#1]
This isn't implemented in master/pycharm_community but is only a pull request away. I haven't quite decided if it is a good idea yet ... plus I need to test it out ...

**Comment by klondikemarlen** [comment]
https://github.com/klondikemarlen/chocolatey-packages-automatic/compare/pycharm_community...klondikemarlen:install_all_users?expand=1

**Comment by mastacheata** [comment]
Have you seen any other choco packages do this?
Maybe you should put that up for discussion on the choco mailinglist for broader participation and more insight on how others think about this.
This could indeed be a good thing for companies with roaming profiles or shared computers, but I doubt anyone at home will ever notice the existence of the "All UIsers" start menu in Windows at all.

**Comment by klondikemarlen** [comment]
I don't really know if anyone else does this. The installer from the company would probably be responsible to implement it automatically or through as silent install variable https://stackoverflow.com/a/35947853. PyCharm allows install for everyone but only through the GUI install (as far as I know). I am not really sure how to test it either ... maybe looking at the source code?

I personally implemented it because Chocolatey installs as Admin while I run a regular user account (with Admin for Admin tasks). So when I upgrade PyCharm ... I end up with no start menu shortcut. So I end up having to create the shortcut manually. Which I find annoying.

**Comment by klondikemarlen** [comment]
I posted on https://groups.google.com/forum/#!forum/chocolatey. I'll let you know if I get any feedback and link to my post when it gets approved.
